name: CI for yppm
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains multiple jobs for different operating systems
jobs:

  macos_Build:
    name: Mac OS Build
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Unlink gcc@9 
      - name: Unlink gcc
        run: brew unlink gcc@9
      
      # Install netCDF
      - name: Install netCDF 
        run: HOMEBREW_NO_AUTO_UPDATE=1 && brew install netcdf  
      
      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version

      # Install GPTL
      - name: Install GPTL
        run: |
          cd /tmp
          export CC=gcc-10
          export FC=gfortran-10
          wget https://github.com/jmrosinski/GPTL/releases/download/v8.0.3/gptl-8.0.3.tar.gz
          tar -xzvf gptl-8.0.3.tar.gz
          cd gptl-8.0.3
          ./configure
          make
          make check
          sudo make install
      
      # Test debug mode 
      - name: Test yppm Debug 
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-10
          export FC=gfortran-10
          cmake -DCMAKE_BUILD_TYPE=debug ..
          make
          ctest
          make install
          
      # Test release mode 
      - name: Test yppm Release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-10
          export FC=gfortran-10
          cmake -DCMAKE_BUILD_TYPE=release ..
          make
          ctest       
          make install

      # Test GPTL support
      - name: Build yppm with GPTL profiling
        run: |
          cd ref
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_10.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_20.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_30.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_10.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_20.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_30.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7.nl
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-10
          export FC=gfortran-10
          cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_GPTL=1 -DENABLE_AUTOPROFILING=1 ..
          make
          ctest
          grep yppm_core_mod_MOD_yppm test/timing.000000 

  ubuntu_build:
    name: Ubuntu Build
    # Run on ubuntu-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2
        with:
          lfs: true

      # Update
      - name: Update
        run: sudo apt-get update

      # Install NetCDF
      - name: Install NetCDF
        run: sudo apt-get install libnetcdf-dev -y

      # Install NetCDF-Fortran
      - name: Install NetCDF-Fortran
        run: sudo apt-get install libnetcdff-dev -y

      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version

      # Install GPTL
      - name: Install GPTL
        run: |
          cd /tmp
          wget https://github.com/jmrosinski/GPTL/releases/download/v8.0.3/gptl-8.0.3.tar.gz
          tar -xzvf gptl-8.0.3.tar.gz
          cd gptl-8.0.3
          ./configure
          make
          make check
          sudo make install

      # Test debug mode
      - name: Build yppm debug
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=debug ..
          make
          ctest
          make install

      # Test release mode
      - name: Build yppm release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=release ..
          make
          ctest
          make install

      # Test GPTL support
      - name: Build yppm with GPTL profiling
        run: |
          cd ref
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_10.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_20.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12_30.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.0.12.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_10.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_20.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7_30.nl
          sed -i -e 's/do_profile=0/do_profile=1/' test/test_input/yppm_0.1.7.nl
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_GPTL=1 -DENABLE_AUTOPROFILING=1 ..
          make
          ctest
          grep yppm_core_mod_MOD_yppm test/timing.000000 
