name: CI for yppm
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains multiple jobs for different operating systems
jobs:

  macos_Build:
    name: Mac OS Build
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Install homebrew 
      - name: Install Homebrew 
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      # Install GCC 
      - name: Install GCC
        run: brew install gcc
        
      # Install gfortran
      - name: Install gfortran
        run: brew install --cask gfortran
        
      # Install netCDF
      - name: Install netCDF 
        run: brew install netcdf 
            
      # Install CMake
      - name: Install CMake
        run: brew install cmake
      
      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version
      
      # Test debug mode 
      - name: Test c_sw Debug 
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-10
          export FC=gfortran          
          cmake -DCMAKE_BUILD_TYPE=debug ..
          make
          ctest
          
      # Test release mode 
      - name: Test c_sw Release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc-10
          export FC=gfortran          
          cmake -DCMAKE_BUILD_TYPE=release ..
          make
          ctest       
       
  ubuntu_build:
    name: Ubuntu Build
    # Run on ubuntu-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2
        with:
          lfs: true

      # Install NetCDF
      - name: Install NetCDF
        run: sudo apt-get install libnetcdf-dev -y

      # Install NetCDF-Fortran
      - name: Install NetCDF-Fortran
        run: sudo apt-get install libnetcdff-dev -y

      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version
      # Test debug mode
      - name: Build c_sw debug
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=debug ..
          make
          ctest
      # Test release mode
      - name: Build c_sw release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=release ..
          make
          ctest
